server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: vehicle-ms
          uri: lb://vehicle-ms
          predicates:
            - Path=/Vehicles/**
        - id: repair-ms
          uri: lb://repair-ms
          predicates:
            - Path=/Repairs/**
        - id: log-ms
          uri: lb://log-ms
          predicates:
            - Path=/Logs/**
        - id: report-ms
          uri: lb://report-ms
          predicates:
            - Path=/Reports/**

  